name: earning_app
description: Earn coins via tasks and withdraw via local methods. Mobile app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.4
  firebase_analytics: ^11.2.1
  firebase_remote_config: ^5.1.2
  firebase_messaging: ^15.1.3
  firebase_crashlytics: ^4.1.3
  firebase_storage: ^12.3.2
  google_sign_in: ^6.2.2
  url_launcher: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^3.1.2
  intl: ^0.19.0
  dio: ^5.7.0
  device_info_plus: ^11.0.0
  package_info_plus: ^8.0.0
  google_mobile_ads: ^5.1.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/payment_icons/bkash.png
    - assets/payment_icons/nagad.png
    - assets/payment_icons/rocket.png
    - assets/payment_icons/upay.png
    - assets/payment_icons/paytm.png
    - assets/lottie/success.json
    - assets/lottie/empty.json
